services:
  - type: web
    name: resume-screening
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn resume_project.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DB_ENGINE
        value: "sqlite"
